### ISSUE TITLE
Automate the loading of Stats NZ Admin boundaries

### ISSUE THREAD

**Issue by jason-bedford** [linz/AdminBoundaries#15]
Stats NZ have changed the way they deliver the Meshblock, Concordance, and TA layers, from FTP to their Datafinder system.

We need to investigate if there's a better way to automate the loading of these layers, available from the following URLs:
https://datafinder.stats.govt.nz/layer/40077-statsnz-meshblock/
https://datafinder.stats.govt.nz/table/40083-stats-meshblock-concordance/
https://datafinder.stats.govt.nz/layer/39939-statsnz-ta/

These are restricted layers, but jramsay@linz.govt.nz and myself have been granted access.
Is there a group email which could be used instead?

In the meantime I'll continue the existing process of downloading these layers to the FTP drive.

**Comment by imincik** [comment]
@jrlinz , hold fire on this one. We need to talk about best way how to do it. But you are welcome to come with some proposal.

**Comment by imincik** [comment]
@jason-bedford , @jrlinz , would you please ask Stats to grant access for myself as well ?

**Comment by jason-bedford** [comment]
@imincik you should have access now.

**Comment by imincik** [comment]
Thanks @jason-bedford

**Comment by ghost** [comment]
@imincik whats to discuss? Stats are providing their layers as a Kx style data service, we need to alter our collection method. What they've done is a good thing. Previously the files were prepared manually and often had to be manipulated before import. This takes away a major source of error

My proposal: Adapt some of the LDS-Replicate download code as a module and include it alongside the current AdminBoundaries code.

**Comment by imincik** [comment]
@jrlinz , is it done ? If not, would you please provide update on this task ?

**Comment by ghost** [comment]
@jason-bedford Can you take a look on TST2 pls. Have a new version up and running. If you agree that its working I'll deploy to PRD3

**Comment by ghost** [comment]
table_version bug fixed, pls retest

**Comment by jason-bedford** [comment]
Tested, and no errors were reported.

**Comment by ghost** [comment]
Testing auto updates and notifications

**Comment by ghost** [comment]
Production deployment tasks;
1. change the meshblock_concordance column names
2. install postgresql-server-dev-9.3 (libpq5) to get table_version up to date
3. replace the admin boundaries web application

**Comment by ghost** [comment]
Complete
