### ISSUE TITLE
Rename repository to 'linz-admin-boundaries-ui'

### ISSUE THREAD

**Issue by imincik** [linz/AdminBoundaries#20]
Rename repository to 'linz-admin-boundaries-ui' once Python code migration will be finished to `linz-admin-boundaries-uploader` repo.

**Comment by imincik** [comment]
@jrlinz , I found this repository: https://github.com/linz/linz-admin-boundaries-ui. Looks empty. would you please provide an update on this task ?

Thanks

**Comment by ghost** [comment]
Renamed
