### ISSUE TITLE
Provide testing for AdminBoundaries::UserAdmin AIMS database modules

### ISSUE THREAD

**Issue by ghost** [linz/AdminBoundaries#23]
Write unittests for UserAdmin modules

**Comment by ghost** [comment]
gradle build had to be updated along with deps and unitests (which had broken). Have repaired this for DABConnector. Will also need to mock pg tests which are set to a local pg instance. Also lookiing at config reader and servlet formatter test failures

**Comment by josephramsay** [comment]
Tests written against primary functionality.
Considering adding per function tests AND reducing state dependencies

**Comment by ghost** [comment]
Done for functional tests
