### ISSUE TITLE
Build tomcat-users.xml edit functionality as an AdminBoundaries::UserAdmin module

### ISSUE THREAD

**Issue by ghost** [linz/AdminBoundaries#25]
Create User view with add/del/edit for tomcat-users.xml as a module in AdminBoundaries so that AIMS admin can review and edit their users.
[Currently this function is performed with a bash script using a geoserver admin account]

**Comment by imincik** [comment]
Isn't it better to have this ticket in admin-bdys repo ?

**Comment by ghost** [comment]
@imincik Yes probably. Looks like the beta transfer function is dropping all associations though... *sigh*

**Comment by josephramsay** [comment]
Added edit with sha256 encryption. Tested login with new encrypted but extended ($0$...) pw works correctly
