### ISSUE TITLE
Build AIMS database access functionality as an AdminBoundaries::UserAdmin module

### ISSUE THREAD

**Issue by ghost** [linz/AdminBoundaries#26]
Create User view with add/del/edit for access to aims_dba/user/admn/reader groups as a module in AdminBoundaries so that AIMS admin can review and edit their database users.

**Comment by imincik** [comment]
Probably move this admin-bdys repo.

**Comment by josephramsay** [comment]
Added db connectivity. Had to create new realm in context.xml for dab user with elevated group assignment privs
