### ISSUE TITLE
Provide interface for updating API users

### ISSUE THREAD

**Issue by SPlanzer** [linz/AdminBoundaries#29]
It would be very useful to also add an interface for managing the API users. 

Currently there are scripts to do this but an interface for AIMS admins would stream line this and remove data services from managing AIMS users. 
* https://github.com/linz/AIMS/blob/master/utils/createUsers.py
* https://github.com/linz/AIMS/blob/master/utils/updateUser.py
* https://github.com/linz/AIMS/blob/master/utils/deleteUser.py

User API endpoints are documented in the AIMS documentation as hosted on the server on the AIMS server (http://<prd_web_server>:8080/aims/doc/users)

**Comment by ghost** [comment]
@SPlanzer  Looking at the scripts I'd assume the AIMS user reg can be achieved with one crafted http/json request. 
1. Are there any UI actions that need to be performed? 
2. Do you need the response returned or is it just for confirmation?

**Comment by ghost** [comment]
There are a couple of ways to do this. 
1. Direct http/json calls to the API (requires stored/collected creds)
2. Bundle and access User data through AIMS/UserDao (lnking AIMS libs heavyweight solution)
2. Bundle and access User data through AIMS/DBUtils (lnking AIMS libs heavyweight solution possibly bypassing validation checks)
4. Directly into the database (unwise as it bypasses security/validation)

**Comment by ghost** [comment]
Interfacing json api since easier but will still look at direct connect through AIMS backend

**Comment by ghost** [comment]
@SPlanzer You might have encountered this. In the AIMS API docs email is a required user field but I've been testing the API on tst1 and email isn't returned in the json response. Is it a hidden field or has it never been set? (assume tst2 snapshot from prd3 reflects the production situation) The old createUser.py script you use has it set to ""

**Comment by SPlanzer** [comment]
There has been no real development against this API endpoint therefore very little testing. This sounds like a AIMS bug to me. 

In this respect the tst2 snapshot should reflect production

**Comment by ghost** [comment]
This is mostly done, just have to; 
- [x] Tidy up UI (components non-uniform and poorly arranged)
- [x] Improve documentation/comments
- [x] Remove debugging code
- [ ] Transfer user credentials to AIMS requests
...possible additional development
- [ ] Direct connect AIMS not via API

**Comment by ghost** [comment]
Can be viewed here http://\<tst2\>:8080/ab/usr

**Comment by ghost** [comment]
Ready for UI testing

**Comment by ghost** [comment]
@SPlanzer suggested new requirement, [Restart] function to reload tomcat user database

**Comment by ghost** [comment]
Restart button added though might not be needed as webapp reload seems to reset user list. this function has also been added. Sent to @jason-bedford for user testing

**Comment by josephramsay** [comment]
Functionality added with API calls rather than direct access into aims instance. 
TODO user creds transfer from dab login to api interface

**Comment by ghost** [comment]
Done and tested. Won't bypass API as may also bypass AIMS level security/side-effects
