### ISSUE TITLE
Upload FENZ Localities Layer from LDS

### ISSUE THREAD

**Issue by jason-bedford** [linz/AdminBoundaries#33]
The way that FENZ provide us with Localities data has changed. 
Previously they would send us a link to download the data, which we would save to \\ad.linz.govt.nz\dfs\Geodata\GISData\NZ Localities.
The Downloader for Admin Boundarys would then check this folder for changes.

This has changed so that now the Localities layer is available via the LDS - https://data.linz.govt.nz/layer/104830-fire-and-emergency-nz-localities/.

Can we please make a change to the Downloader for Admin Boundarys to have it check the LDS instead of the network directory.
This will be a similar process as to how the Meshblock and TA layers are loaded from the Stats NZ Datafinder.

**Comment by YingtingChen** [comment]
Changes have been made to load locality layer from LDS. 
see PR: https://github.com/linz/linz-admin-boundaries-uploader/pull/36 and https://github.com/linz/linz-admin-boundaries-ui/pull/34
